### ISSUE TITLE
简历要点

### ISSUE THREAD

**Issue by Golden-time** [ybbdaidai/interview#2]
**一些关键点**
求职意向：企业一般不关注
工作经验、社会实践：可写实习经验
课程：可不写，如果写要写与应聘职业相关的主修课程
爱好专长：如精通什么语言，写与职位相关的爱好特长

**模版**
[怎样写好一份好的技术简历](https://github.com/geekcompany/ResumeSample/blob/master/web.md)

**Comment by boyiFan** [comment]
文件名和格式
	•	简历文件命名： 姓名+经验职位+联系方式 
	•	pdf 格式最佳。 
个人信息
	•	重要信息写在显眼的位置： 
	◦	基本信息两三行搞定包括姓名，联系方式，工作年限，性别，学历。
	◦	例如： 
	▪	李三 | 130xxxxxxxx | lisan@163.com | 2年前端
	▪	男 | 1991.01.10 | 未婚 | xx大学 | 目前在杭州 | 意向：杭州
	•	重点描述当前的职位和工作状态： 
	◦	“目前负责电商类型项目的前端开发，团队一共5人，我主要负责框架和核心业务实现。”
